version: '1'

services:
  microservicio:
    image: myapp:latest
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@cuf994bzm4b1se1i_tp?TNS_ADMIN=/app/Wallet_BD_Prueba/
      - spring.datasource.username=ADMIN
      - spring.datasource.password=OracleCloud123
    restart: always